{"name": "test_loginfail", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'allureLogs'", "trace": "self = <tests.test_login.test_login testMethod=test_loginfail>\n\n    @pytest.mark.run(order=2)\n    def test_loginfail(self):\n>       cl.allureLogs(\"App Launched\")\nE       AttributeError: 'function' object has no attribute 'allureLogs'\n\ntest_login.py:27: AttributeError"}, "start": 1739876571448, "stop": 1739876571449, "uuid": "c4252b0e-395a-41de-93ed-2b1e9971a404", "historyId": "b564db8fe7180511f5c38870cd3f148d", "testCaseId": "b564db8fe7180511f5c38870cd3f148d", "fullName": "test_login.test_login#test_loginfail", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "test_login"}, {"name": "host", "value": "Chinmayi"}, {"name": "thread", "value": "13636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}